FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    automake \
    autoconf \
    erlang-dev \
    erlang-nox \
    elixir \
    rebar3 \
    libssl-dev \
    libexpat1-dev \
    libyaml-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src
RUN git clone --branch 22.05 https://github.com/processone/ejabberd.git

WORKDIR /usr/src/ejabberd
RUN ./autogen.sh && \
    ./configure && \
    make && \
    make install

RUN mkdir -p /var/log/ejabberd /var/lib/ejabberd /etc/ejabberd /home/xmpp/tarea2

RUN useradd -m -d /home/xmpp -s /bin/bash xmpp

RUN chown -R xmpp:xmpp /var/log/ejabberd /var/lib/ejabberd /etc/ejabberd /home/xmpp /usr/local/sbin/ejabberd* /usr/local/lib/ejabberd* /usr/local/var/ /usr/local/etc/ejabberd

RUN cp /usr/src/ejabberd/ejabberd.yml.example /usr/local/etc/ejabberd/ejabberd.yml \
       && chown xmpp:xmpp /usr/local/etc/ejabberd/ejabberd.yml

EXPOSE 5222 5280

USER xmpp

CMD ["ejabberdctl", "foreground"]
