FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    make \
    gcc \
    g++ \
    autoconf \
    automake \
    erlang \
    erlang-dev \
    libyaml-dev \
    libexpat1-dev \
    libsqlite3-dev \
    zlib1g-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

RUN git clone --branch 22.05 https://github.com/processone/ejabberd.git && \
    cd ejabberd && \
    ./autogen.sh && \
    ./configure --enable-user=root && \
    make && \
    make install && \
    cd .. && \
    rm -rf ejabberd

EXPOSE 5222 5269 5280



CMD ["ejabberdctl", "foreground"]
